Add support for Symfony 5 / admin 4
sonata-project/SonataFormatterBundle pull request #641
Opened 2022-01-06 13:58 UTC by jorrit

## Subject

Add support for Symfony 5, Sonata Admin 4,  Twig 3.

Closes #463.

## Changelog

```markdown
### Added
- Added support for Symfony 5 / Sonata Admin 4 / Twig 3.
```
## To do

- [ ] Make sure everything works.

2022-01-07 08:45 UTC, VincentLanglet commented on src/Form/Type/FormatterType.php
> +    public function __construct(PoolInterface $pool)
You need to update the conf isnt it ?

2022-01-07 10:17 UTC, jordisala1991 requested changes

2022-01-07 10:17 UTC, jordisala1991 commented on composer.json
> +        "symfony/config": "^4.4 || ^5.1",
instead of 5.1 you should use 5.3 for all symfony packages

2022-01-07 10:17 UTC, jordisala1991 commented on composer.json
> +        "symfony/phpunit-bridge": "^5.1.8 || ^6.0"
this one only 6.0

2022-01-07 10:17 UTC, jordisala1991 commented on composer.json
> +        "twig/twig": "^2.12.1 || ^3"
```suggestion
        "twig/twig": "^2.12.1 || ^3.0"
```

2022-01-07 10:17 UTC, jordisala1991 commented on composer.json
> +        "sonata-project/admin-bundle": "^3.98.2 || ^4",
```suggestion
        "sonata-project/admin-bundle": "^4.0",
```

2022-01-07 10:17 UTC, jordisala1991 commented on composer.json
>      "conflict": {
you can remove conflict with core bundle

2022-01-07 10:17 UTC, jordisala1991 commented on composer.json
>          "sonata-project/form-extensions": "^0.1 || ^1.4",
you can leave only 1.4

2022-01-07 11:55 UTC, jorrit commented
Thanks for your review, @jordisala1991  !

2022-01-07 11:59 UTC, jordisala1991 commented
Can you edit the workflow file?

You need to add symfony 5.3 and 5.4. It will need also a dev-kit PR, but we would like to see if all the build pass.

It would also be nice if you try to add symfony 6.0 to the composer.json too (and on the workflow file)

2022-01-07 12:03 UTC, jorrit commented
Is the build variant for sonata-project/block-bundle:"3.*" still relevant? If not, I think I need to create a PR on devkit.

2022-01-07 12:09 UTC, jorrit commented
friendsofsymfony/ckeditor-bundle is not ready for Symfony 6.

2022-01-07 12:14 UTC, VincentLanglet commented
> Is the build variant for sonata-project/block-bundle:"3.*" still relevant? If not, I think I need to create a PR on devkit.

It's not relevant, we cannot support both sonata admin 3 and 4. And Sonata admin 4 only use block 4.

2022-01-07 12:19 UTC, jordisala1991 commented on composer.json
> +        "symfony/config": "^4.4 || ^5.3 || ^6.0",
if ckeditor bundle is not compatible yet, please forget my previous comment about adding 6.0 to composer.json, revert to only 4.4 and 5.3

2022-01-07 12:25 UTC, jorrit commented on composer.json
> +        "symfony/config": "^4.4 || ^5.3 || ^6.0",
I reverted it.

2022-01-07 12:29 UTC, VincentLanglet commented
There will be https://github.com/FriendsOfSymfony/FOSCKEditorBundle/pull/239 to follow

2022-01-07 13:24 UTC, VincentLanglet commented
> There will be [FriendsOfSymfony/FOSCKEditorBundle#239](https://github.com/FriendsOfSymfony/FOSCKEditorBundle/pull/239) to follow

Merged, but their looking for a maintainer...

2022-01-10 09:06 UTC, jorrit commented
Perhaps we should not wait for a new release for the CKEditor bundle and add support for Symfony 5 now, and Symfony 6 when CKEditor is updated.

2022-01-10 09:45 UTC, jordisala1991 commented
> Perhaps we should not wait for a new release for the CKEditor bundle and add support for Symfony 5 now, and Symfony 6 when CKEditor is updated.

Can you open a dev-kit PR with the needed changes too?

2022-01-10 09:46 UTC, jordisala1991 commented on tests/DependencyInjection/SonataFormatterExtensionTest.php
> +            \Twig\Loader\LoaderInterface::class,
Add this as a use please

2022-01-10 09:51 UTC, jorrit commented on tests/DependencyInjection/SonataFormatterExtensionTest.php
> +            \Twig\Loader\LoaderInterface::class,
ok!

2022-01-10 09:53 UTC, jorrit commented
The dev-kit PR has been created.

2022-01-10 10:13 UTC, VincentLanglet requested changes

2022-01-10 10:13 UTC, VincentLanglet commented on tests/Block/FormatterBlockServiceTest.php
>          if (!class_exists('Sonata\BlockBundle\Block\Service\AbstractAdminBlockService')) {
This test can be removed if we remove the support of block bundle 3

2022-01-10 10:22 UTC, jorrit commented
Done. I see two more tests marked `@group legacy`. When I remove those annotations, no deprecations show up in the test output. Can/should those annotations be removed in that case?

2022-01-10 10:31 UTC, VincentLanglet approved these changes

2022-01-10 10:35 UTC, VincentLanglet commented
> Done. I see two more tests marked `@group legacy`. When I remove those annotations, no deprecations show up in the test output. Can/should those annotations be removed in that case?

Seems like there is more tests with group legacy https://github.com/sonata-project/SonataFormatterBundle/search?q=legacy ; at least on the default branch. I don't have the project locally to check if there is more.
Some of them have NEXT_MAJOR comment to help knowing what to do.

For tests without next major comment, the question would be to know why there is a group legacy. If you know why and it's not needed anymore you can remove the group. Anyway it can still be done in another PR. The stable release will be done after
- Adding param/return type everywhere
- Bumping Phpstan/psalm to good enough levels.
- Solving all the next major comment
- Mark as final as possible classes

2022-01-10 11:59 UTC, jorrit commented
I'm working on the 5.x branch and all the NEXT_MAJOR comments have been addressed. This leaves 2 legacy groups:

 * FormatterValidatorTest::testInvalidCase: Can't find why this one is legacy.
 * SonataFormatterExtensionTest::testLoadWithoutDefaultFormatter: I don't think this test case makes sense anymore because the deprecation it tested was marked as `NEXT_MAJOR: remove this if block` and removed in 4.x.

2022-01-10 12:00 UTC, jordisala1991 approved these changes

2022-01-10 13:14 UTC, merged

2022-01-10 13:17 UTC, VincentLanglet commented
> I'm working on the 5.x branch and all the NEXT_MAJOR comments have been addressed. This leaves 2 legacy groups:
> 
> * FormatterValidatorTest::testInvalidCase: Can't find why this one is legacy.
> * SonataFormatterExtensionTest::testLoadWithoutDefaultFormatter: I don't think this test case makes sense anymore because the deprecation it tested was marked as `NEXT_MAJOR: remove this if block` and removed in 4.x.

I've merge the dev-kit PR and this one but a new PR to remove the legacy group is welcomed.

Also, if you wanna work on the stable release of 5.0, it's welcomed too. We (@jordisala1991 and I) can help you about the TODO-list.